# Generated by Django 4.1.7 on 2023-08-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
